"""messages

Revision ID: b3d0ca50c530
Revises: 8e8ffb16f5a0
Create Date: 2024-10-25 16:34:55.073056

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b3d0ca50c530'
down_revision: Union[str, None] = '8e8ffb16f5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'messages',
        sa.Column('id', sa.Integer, primary_key=True, nullable=False),
        sa.Column('message', sa.String, nullable=False),
        sa.Column('sender_id', sa.Integer, sa.ForeignKey('user.id'), nullable=False),
        sa.Column('receiver_id', sa.Integer, sa.ForeignKey('user.id'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
